# Site Settings
title: Thanh NT Resume
description: Thanh NT Resume
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: NGO TIEN THANH
tagline: Mobile Developer
pic: avatar.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm 24 years old Mobile Developer of Agiletech Viet Nam. I have more than 2 years of work experience in various positions. I love coding, music, swimming, gym and game. Self-motivated and hardworking developer with the love of information technology
Can work well under pressure and to quickly acquire new technology and new programming language."

#sidebar links
email: thanh@agiletech.com
phone: 097 599 5208
website: agiletech.vn #do not add http://
github: thanhkma1594
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
